### ISSUE TITLE
rudi:register-providers not working on Windows

### ISSUE THREAD

**Issue by fajkovicsasa** [vsmid/rudimentary#12]
OS: Windows 10 Pro, OS build: 18363.592
IDE: IntelliJ IDEA 2019.3.1 (Ultimate Edition) Build #IU-193.5662.53, built on December 18, 2019

Steps to reproduce:
1. Following the tutorial, executed the command `mvn rudi:new-endpoint -DclassName=HelloWorldEndpoint -Dpackage=app`
2. Run (double click) rudi:register-providers from maven tool windows

Error:
Failed to execute goal hr.yeti.rudimentary:rudimentary-maven-plugin:1.0-SNAPSHOT:register-providers (default-cli) on project hello-world: Execution default-cli of goal hr.yeti.rudimentary:rudimentary-maven-plugin:1.0-SNAPSHOT:register-providers failed: Unexpected internal error near index 1
\

Same happens when executing through terminals (tested on Git Bash, Command Prompt and PowerShell)

**Comment by vsmid** [comment]
Hi, 

thanks for reporting this. I was aware of possible problems with WinOs since I don't have it :-)
I have pushed what I think should fix the problem. 

Can you please try it again?

**Comment by fajkovicsasa** [comment]
Can confirm it works now.

**Comment by vsmid** [comment]
Thanks!
